services:
  mysql:
    image: mysql:8.0
    container_name: x_like_mysql
    restart: always
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password